# ____        _              _____           _
#/ ___| _ __ (_) ___ _   _  |_   _|__   ___ | |___
#\___ \| '_ \| |/ __| | | |   | |/ _ \ / _ \| / __|
# ___) | |_) | | (__| |_| |   | | (_) | (_) | \__ \
#|____/| .__/|_|\___|\__, |   |_|\___/ \___/|_|___/
#      |_|           |___/
# Useful links:
# Documentation: https://hhitt-1.gitbook.io/spicytools
# Discord for support, suggestions & more: https://discord.com/invite/W7R3mPXzQ7
# MiniMessage tool that make it faster ;) https://webui.advntr.dev/

Alert:
  # Alert is a message sent to all online players (also to console)
  # You can choose Message, Title or ActionBar
  Prefix: "<b><color:#ff3037>[Alert]</color></b>"
  Mode: Message

Broadcast:
  # Same as Alert but without the plugin prefix
  # You can choose Message, Title or ActionBar
  Mode: Message
  # Choose if you want to send a Title or a SubTitle while the mode is set on Title
  While-Title: Subtitle

Lobby:
  Lobby-Server: "MySuperLobby"
  Pre-Connect-Message: "<green>Teleporting to the lobby...</green>"
  Post-Connect-Message: "<gold>Connected to lobby!</gold>"
  Already-Connected: "<red>You are already connected to the lobby!</red>"

Find:
  Player-Found: "<color:#7aff81>The player <color:#ffbc4f>%player%</color> is connected at the server <color:#ffbc4f>%server%</color>.</color>"

Global-List:
  Total: "<color:#ffbc4f>The total amount of player(s) is: <color:#ff00b7>%playercount%</color></color>"
  Per-Server: "<color:#b9ff5e>The amount of player(s) for the server <color:#b27aff>%server%</color> is: <color:#ffbc4f>%playercount%</color></color>"

Catch:
  Sender: "<color:#7aff81>You caught the player <color:#ff775c>%player%</color></color>"
  Caught-Player: "<color:#7aff81>You was caught by <color:#b9ff5e>%sender%</color> to the server <color:#ff775c>%server%</color></color>"

Messages:
  Wrong-Command-Usage: "<red>Wrong Command. Use <gold>/Spicytools help</gold>.</red>"
  Player-Not-Found: "<red>Player not found or offline!</red>"
  No-Permission: "<red>You don't have permission to perform this command!</red>"
  Reload-Config: "<blue>Config.yml file has been reloaded successfully!</blue>"
  Help: "<red>Please, read the docs to know which are the commands and their usage.</red> <green>https://hhitt-1.gitbook.io/velocity-tools/</green>"
  Already-Connected: "<red>The player is already connected to this server!</red>"
  Must-Be-Player: "<red>Only players can run this command!</red>"
  Server-Not-Found: "<red>Server not found!</red>"
  Player-Sender: "<green>You have sent <blue>%player%</blue> to the server <gold>%server%</gold></green>"
  Player-Sent: "<gold>You have been forced sent to this server (<red>%server%</red>) by a Staff (<blue>%player%</blue>)!</gold>"

